/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IdentityFactoryInterface extends utils.Interface {
  functions: {
    "deployIdentity()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "deployIdentity"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployIdentity",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "deployIdentity",
    data: BytesLike
  ): Result;

  events: {
    "IdentityDeployed(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "IdentityDeployed"): EventFragment;
}

export interface IdentityDeployedEventObject {
  _contract: string;
  _owner: string;
}
export type IdentityDeployedEvent = TypedEvent<
  [string, string],
  IdentityDeployedEventObject
>;

export type IdentityDeployedEventFilter =
  TypedEventFilter<IdentityDeployedEvent>;

export interface IdentityFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IdentityFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployIdentity(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  deployIdentity(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deployIdentity(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "IdentityDeployed(address,address)"(
      _contract?: PromiseOrValue<string> | null,
      _owner?: PromiseOrValue<string> | null
    ): IdentityDeployedEventFilter;
    IdentityDeployed(
      _contract?: PromiseOrValue<string> | null,
      _owner?: PromiseOrValue<string> | null
    ): IdentityDeployedEventFilter;
  };

  estimateGas: {
    deployIdentity(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployIdentity(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
