/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC725X__factory } from "./IERC725X__factory";
export { IERC725Y__factory } from "./IERC725Y__factory";
