/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as custom from "./custom";
export type { custom };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ERC725 } from "./ERC725";
export type { ERC725XCore } from "./ERC725XCore";
export type { ERC725YCore } from "./ERC725YCore";
