/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as custom from "./custom";
export * as interfaces from "./interfaces";
export { ERC725__factory } from "./ERC725__factory";
export { ERC725XCore__factory } from "./ERC725XCore__factory";
export { ERC725YCore__factory } from "./ERC725YCore__factory";
